name: oss_public_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - ipykernel
  - ipython
  - jupyterlab=3.5
  - matplotlib=3.4
  - numpy=1.21
  - pandas=1.0
  - pyarrow=3.0
  - xlrd=1.2
  - scikit-learn=1.0
  - seaborn=0.11
  - statsmodels==0.13
  - pyyaml==5.1
